### ISSUE TITLE
test_pytest.yml does not use `build_dockerfile`

### ISSUE THREAD

**Issue by katporks** [hotosm/gh-workflows#43]
Whent the `"test_pytest.yml"` action is given input for a `build_dockerfile` that is not the default `"Dockerfile"` (i.e. `"Dockerfile.dev"`), the following error occurs:

`Error: buildx failed with: ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory`

When we follow the default `Dockerfile`, the action continues. The issue is that the `build_dockerfile` input is overlooked.

Thank you!

**Comment by spwoodcock** [comment]
Thanks for picking this up!! 🙏 
Will be fixed in v1.2.2 of the workflows.
